# NOTE THIS IS A WORK IN PROGRESS AND WILL BE IN PART 2 OF THE PRESENTATION
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '{your azure subscription guid here}'
  environmentNumber: 1
  environmentName: dev

stages:
- stage: Build
  displayName: 'Build bicep script'
  jobs:  
  - job: Build
    displayName: 'Build bicep script'
    steps:
      - script: echo Hello, world!
        displayName: 'Run Build steps'

      - task: CopyFiles@2
        displayName: 'Include templates in the artifact'
        inputs:
          SourceFolder: 'src'
          Contents: |
            main.bicep
            main.parameters.json
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'      

- stage: DEV
  jobs:
  - job: Deploy
    steps:

    - task: DownloadBuildArtifacts@0
      displayName: 'Download artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    
    - task: AzureCLI@2
      displayName: 'Deploy Bicep file'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |     
          az account set --subscription $(azureSubscription) \    
          az deployment sub create --location uksouth --template-file main.bicep \ 
            --parameters \
              location=uksouth \
              baseApplicationName=shiftleft \
              environmentName=$(environmentName) \
              environmentNumber==$(environmentNumber)
              
